name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      # Install dependencies
      - name: Install Dependencies
        run: composer install

      # Run linter
      - name: Run PHP Linter
        run: ./vendor/bin/phpcs --standard=PSR12 src/

      # Run unit tests
      - name: Run PHPUnit
        run: ./vendor/bin/phpunit

      # Build Docker image
      - name: Build Docker Image
        run: docker build -t my-php-app .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker tag my-php-app my-dockerhub-username/my-php-app:latest
          docker push my-dockerhub-username/my-php-app:latest
